### ISSUE TITLE
Seminario2-revDartagnan

### ISSUE THREAD

**Issue by ddfarias** [JPWALLY2/Doce_Entrega#4]
- revisar funcionalidades para nível de trabalho de conclusão de curso

- analisar detalhadamente funções que podem atender outros clientes além do utilizado como estudo de caso

**Comment by JPWALLY2** [comment]
novas funcionalidades como cadastro e login de fornecedores e acompanhamento da localização do pedido

**Comment by JPWALLY2** [comment]
há funções que podem atender os administradores com fazer o pedido aos fornecedores
